spring.application.name=product-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/products_db
spring.datasource.username=app
spring.datasource.password=app

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
